<a href="https://colab.research.google.com/github/nazirumar/Krish-Naik-Online-NLP-Course/blob/main/Word_embedding_Techniques.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### Word Embedding Techniques using Embedding Layer in Keras

In [ ]:
### Libraries USed Tensorflow> 2.0  and keras

In [1]:
!pip install tensorflow-gpu

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     |████████████████████████████████| 511.7 MB 6.4 kB/s 
     |████████████████████████████████| 438 kB 70.9 MB/s 
     |████████████████████████████████| 1.6 MB 64.8 MB/s 
     |████████████████████████████████| 5.8 MB 55.3 MB/s 
  Attempting uninstall: tensorflow-estimator
    Found existing installation: tensorflow-estimator 2.8.0
    Uninstalling tensorflow-estimator-2.8.0:
      Successfully uninstalled tensorflow-estimator-2.8.0
  Attempting uninstall: tensorboard
    Found existing installation: tensorboard 2.8.0
    Uninstalling tensorboard-2.8.0:
      Successfully uninstalled tensorboard-2.8.0
  Attempting uninstall: keras
    Found existing installation: keras 2.8.0
    Uninstalling keras-2.8.0:
      Successfully uninstalled keras-2.8.0
  Attempting uninstall: gast
    Found existing installation: gast 0.5.3
    Uninstalling gast-0.5.3:
      Successfully uninstalled gast-0.

In [2]:
import tensorflow as tf
print(tf.__version__)

2.9.1


In [3]:
##tensorflow >2.0
from tensorflow.keras.preprocessing.text import one_hot

In [4]:
### sentences
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good']

In [5]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [6]:
### Vocabulary size
voc_size=500

#### One Hot Representation

In [7]:
onehot_repr=[one_hot(words,voc_size)for words in sent] 
print(onehot_repr)

[[427, 46, 147, 103], [427, 46, 147, 5], [427, 438, 147, 317], [363, 365, 81, 311, 252], [363, 365, 81, 311, 119], [177, 427, 308, 147, 74], [29, 468, 158, 311]]


### Word Embedding Represntation

In [8]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential

In [9]:
import numpy as np

In [10]:
## pre padding
sent_length=8
embedded_docs=pad_sequences(onehot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[  0   0   0   0 427  46 147 103]
 [  0   0   0   0 427  46 147   5]
 [  0   0   0   0 427 438 147 317]
 [  0   0   0 363 365  81 311 252]
 [  0   0   0 363 365  81 311 119]
 [  0   0   0 177 427 308 147  74]
 [  0   0   0   0  29 468 158 311]]


In [11]:
## 10 feature dimesnions
dim=10


In [12]:
model=Sequential()
model.add(Embedding(voc_size,10,input_length=sent_length))
model.compile('adam','mse')

In [13]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 8, 10)             5000      
                                                                 
Total params: 5,000
Trainable params: 5,000
Non-trainable params: 0
_________________________________________________________________


In [14]:
##'the glass of milk',
embedded_docs[0]

array([  0,   0,   0,   0, 427,  46, 147, 103], dtype=int32)

In [15]:
model.predict(embedded_docs[0])

1/1 [==============================] - 0s 78ms/step


array([[-0.04898713,  0.02676809, -0.0292622 ,  0.00895777, -0.0095344 ,
        -0.03707396,  0.01283722,  0.0156354 ,  0.01766429, -0.02549417],
       [-0.04898713,  0.02676809, -0.0292622 ,  0.00895777, -0.0095344 ,
        -0.03707396,  0.01283722,  0.0156354 ,  0.01766429, -0.02549417],
       [-0.04898713,  0.02676809, -0.0292622 ,  0.00895777, -0.0095344 ,
        -0.03707396,  0.01283722,  0.0156354 ,  0.01766429, -0.02549417],
       [-0.04898713,  0.02676809, -0.0292622 ,  0.00895777, -0.0095344 ,
        -0.03707396,  0.01283722,  0.0156354 ,  0.01766429, -0.02549417],
       [ 0.02199962, -0.02709605, -0.00978176,  0.03709323,  0.02613953,
        -0.04173116,  0.00935407, -0.03405546,  0.04438615,  0.03241302],
       [-0.04768651,  0.00566297,  0.03443575, -0.04504567, -0.02409365,
        -0.03452586,  0.02915926, -0.04244149,  0.00789688, -0.00582433],
       [-0.02864064, -0.02370998, -0.03276775, -0.00213872,  0.00828834,
         0.0223207 , -0.03680345, -0.04426513

In [16]:
print(model.predict(embedded_docs))

1/1 [==============================] - 0s 31ms/step
[[[-0.04898713  0.02676809 -0.0292622   0.00895777 -0.0095344
   -0.03707396  0.01283722  0.0156354   0.01766429 -0.02549417]
  [-0.04898713  0.02676809 -0.0292622   0.00895777 -0.0095344
   -0.03707396  0.01283722  0.0156354   0.01766429 -0.02549417]
  [-0.04898713  0.02676809 -0.0292622   0.00895777 -0.0095344
   -0.03707396  0.01283722  0.0156354   0.01766429 -0.02549417]
  [-0.04898713  0.02676809 -0.0292622   0.00895777 -0.0095344
   -0.03707396  0.01283722  0.0156354   0.01766429 -0.02549417]
  [ 0.02199962 -0.02709605 -0.00978176  0.03709323  0.02613953
   -0.04173116  0.00935407 -0.03405546  0.04438615  0.03241302]
  [-0.04768651  0.00566297  0.03443575 -0.04504567 -0.02409365
   -0.03452586  0.02915926 -0.04244149  0.00789688 -0.00582433]
  [-0.02864064 -0.02370998 -0.03276775 -0.00213872  0.00828834
    0.0223207  -0.03680345 -0.04426513 -0.04020549  0.02939837]
  [-0.00898389  0.03454154  0.02097166  0.01136829  0.00340428


In [17]:
embedded_docs[0]

array([  0,   0,   0,   0, 427,  46, 147, 103], dtype=int32)

In [18]:
print(model.predict(embedded_docs)[0])

1/1 [==============================] - 0s 14ms/step
[[-0.04898713  0.02676809 -0.0292622   0.00895777 -0.0095344  -0.03707396
   0.01283722  0.0156354   0.01766429 -0.02549417]
 [-0.04898713  0.02676809 -0.0292622   0.00895777 -0.0095344  -0.03707396
   0.01283722  0.0156354   0.01766429 -0.02549417]
 [-0.04898713  0.02676809 -0.0292622   0.00895777 -0.0095344  -0.03707396
   0.01283722  0.0156354   0.01766429 -0.02549417]
 [-0.04898713  0.02676809 -0.0292622   0.00895777 -0.0095344  -0.03707396
   0.01283722  0.0156354   0.01766429 -0.02549417]
 [ 0.02199962 -0.02709605 -0.00978176  0.03709323  0.02613953 -0.04173116
   0.00935407 -0.03405546  0.04438615  0.03241302]
 [-0.04768651  0.00566297  0.03443575 -0.04504567 -0.02409365 -0.03452586
   0.02915926 -0.04244149  0.00789688 -0.00582433]
 [-0.02864064 -0.02370998 -0.03276775 -0.00213872  0.00828834  0.0223207
  -0.03680345 -0.04426513 -0.04020549  0.02939837]
 [-0.00898389  0.03454154  0.02097166  0.01136829  0.00340428  0.00063904


In [19]:
### Assignment

sent=["The world is a better place",
      "Marvel series is my favourite movie",
      "I like DC movies",
      "the cat is eating the food",
      "Tom and Jerry is my favourite movie",
      "Python is my favourite programming language"
      ]

In [23]:
### Vocabulary size
voc_size=1000

In [24]:
onehot_repr=[one_hot(words,voc_size)for words in sent] 
print(onehot_repr)

[[684, 743, 478, 525, 35, 141], [455, 61, 478, 768, 446, 1], [916, 808, 313, 495], [684, 872, 478, 775, 684, 573], [911, 292, 359, 478, 768, 446, 1], [132, 478, 768, 446, 993, 761]]


In [26]:
## pre padding
sent_length=10
embedded_docs=pad_sequences(onehot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[  0   0   0   0 684 743 478 525  35 141]
 [  0   0   0   0 455  61 478 768 446   1]
 [  0   0   0   0   0   0 916 808 313 495]
 [  0   0   0   0 684 872 478 775 684 573]
 [  0   0   0 911 292 359 478 768 446   1]
 [  0   0   0   0 132 478 768 446 993 761]]


In [27]:
## ndim=10
model=Sequential()
model.add(Embedding(voc_size,10,input_length=sent_length))
model.compile('adam','mse')

In [28]:
model.summary()

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding_1 (Embedding)     (None, 10, 10)            10000     
                                                                 
Total params: 10,000
Trainable params: 10,000
Non-trainable params: 0
_________________________________________________________________


In [29]:
##'the glass of milk',
embedded_docs[0]

array([  0,   0,   0,   0, 684, 743, 478, 525,  35, 141], dtype=int32)

In [30]:
model.predict(embedded_docs[0])

1/1 [==============================] - 0s 35ms/step


array([[-0.03268274,  0.00096001, -0.03216665, -0.03632532,  0.02629528,
         0.04024892,  0.0477975 ,  0.01092696,  0.00593961, -0.02358617],
       [-0.03268274,  0.00096001, -0.03216665, -0.03632532,  0.02629528,
         0.04024892,  0.0477975 ,  0.01092696,  0.00593961, -0.02358617],
       [-0.03268274,  0.00096001, -0.03216665, -0.03632532,  0.02629528,
         0.04024892,  0.0477975 ,  0.01092696,  0.00593961, -0.02358617],
       [-0.03268274,  0.00096001, -0.03216665, -0.03632532,  0.02629528,
         0.04024892,  0.0477975 ,  0.01092696,  0.00593961, -0.02358617],
       [-0.00510947, -0.04432347, -0.04480549, -0.00861651,  0.04983551,
         0.03454346, -0.01016061, -0.03021746, -0.01734721, -0.03508289],
       [ 0.03378569, -0.04601388,  0.01740653, -0.01984128,  0.02298583,
         0.03044888, -0.04183384, -0.0080483 ,  0.00784434, -0.04010233],
       [ 0.02805554,  0.02092567, -0.00466685,  0.04994613, -0.02335277,
        -0.04455182, -0.02420127, -0.00958167

In [31]:
print(model.predict(embedded_docs)[0])

1/1 [==============================] - 0s 30ms/step
[[-0.03268274  0.00096001 -0.03216665 -0.03632532  0.02629528  0.04024892
   0.0477975   0.01092696  0.00593961 -0.02358617]
 [-0.03268274  0.00096001 -0.03216665 -0.03632532  0.02629528  0.04024892
   0.0477975   0.01092696  0.00593961 -0.02358617]
 [-0.03268274  0.00096001 -0.03216665 -0.03632532  0.02629528  0.04024892
   0.0477975   0.01092696  0.00593961 -0.02358617]
 [-0.03268274  0.00096001 -0.03216665 -0.03632532  0.02629528  0.04024892
   0.0477975   0.01092696  0.00593961 -0.02358617]
 [-0.00510947 -0.04432347 -0.04480549 -0.00861651  0.04983551  0.03454346
  -0.01016061 -0.03021746 -0.01734721 -0.03508289]
 [ 0.03378569 -0.04601388  0.01740653 -0.01984128  0.02298583  0.03044888
  -0.04183384 -0.0080483   0.00784434 -0.04010233]
 [ 0.02805554  0.02092567 -0.00466685  0.04994613 -0.02335277 -0.04455182
  -0.02420127 -0.00958167  0.00987234 -0.02386993]
 [-0.00331775 -0.03577051  0.01367005  0.04943633 -0.04625137  0.04441075